# Generated by Django 3.2 on 2021-07-14 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('perfil', models.CharField(max_length=500)),
                ('descripcion', models.CharField(max_length=500)),
                ('duracion', models.IntegerField()),
                ('clase1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Principal.clase')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['nombre'],
            },
        ),
    ]
