# Generated by Django 3.2 on 2021-07-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='clase1',
        ),
        migrations.AddField(
            model_name='curso',
            name='clases',
            field=models.ManyToManyField(to='Principal.Clase'),
        ),
    ]
